### ISSUE TITLE
Resx resource filename capitalization

### ISSUE THREAD

**Issue by jochembroekhoff** [tryashtar/TreeViewAdv#1]
The following resources from `Properties/Resources.resx` do not correspond to the case-matching files, causing issues on case-senstive filesystems:

- `"DVSplit"`: `..\resources\dvsplit.cur` &rarr; `..\Resources\DVSplit.cur`
- `"Leaf"`: `..\resources\leaf.bmp` &rarr; `..\Resources\Leaf.bmp`
- `"unknown"`: `..\resources\unknown.bmp` &rarr; `..\Resources\unknown.bmp`

Stumbled upon this issue when trying to compile https://github.com/tryashtar/nbt-studio on Linux.

**Comment by tryashtar** [comment]
Fixed
